### ISSUE TITLE
0.11.3+ goes to 100% cpu usage

### ISSUE THREAD

**Issue by Hipska** [lomik/carbon-clickhouse#122] opened 2022-11-30 14:28 UTC
I'm using quite the default configuration as in the README.md file and noticed that as of version 0.11.3, carbon-clickhouse goes to 100% cpu usage and no errors or warnings appear in the log file.

The last stable version seems to be 0.11.2 where cpu usage goes to <1%.

**Comment by lexx-bright** [comment] 2022-11-30 14:50
Also noticed this. Raised after 22e83d224d44b6748bedfa078bf478f8982c3a60

**Comment by msaf1980** [comment] 2022-11-30 18:03
I'll plann revert in PR #123 after some testing

**Comment by msaf1980** [comment] 2022-12-01 04:54
Can you test current master ? As I see, no high CPU usage at idle. If worked as expected, I'll release fixed version.

**Comment by lexx-bright** [comment] 2022-12-01 06:08
Can confirm the issue is fixed on the current master.

**Comment by msaf1980** [comment] 2022-12-01 08:58
New version (0.11.5) with fix is released

**Closed as completed** 2022-12-01 11:15 UTC
